run:
  timeout: 5m
  tests: true
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
