name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '{{.go_version}}'
      - name: Cache golangci-lint
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ "{{" }} runner.os {{ "}}" }}-go-${{ "{{" }} hashFiles('**/go.sum') {{ "}}" }}
      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run
      - name: Test
        run: go test ./...
      - name: Build
        run: go build ./...
